#!/bin/sh
# Compiles the SDL_GPU uber-shaders (docs/PORT_POSIX_PLAN.md, T6b.0) and
# regenerates ShaderBlobsSDLGPU.h. The generated header is COMMITTED so the
# normal build needs no shader toolchain at all; run this script only when a
# .vert/.frag changes.
#
# Toolchain (both in the Ubuntu/Debian archives, and in Homebrew on macOS):
#   glslangValidator (glslang-tools)  Vulkan GLSL -> SPIR-V
#   spirv-cross                       SPIR-V      -> MSL for the Metal backend
#
# Binding model (must match RHIDeviceSDLGPU and SDL_gpu.h's documentation):
#   SPIR-V: vertex uniforms = set 1 binding 0; fragment sampled textures =
#           set 2 bindings 0..2; fragment uniforms = set 3 binding 0.
#   MSL:    spirv-cross maps those bindings straight to [[buffer(0)]] /
#           [[texture(0..2)]]/[[sampler(0..2)]], which is exactly where
#           SDL's Metal backend binds them; vertex attributes go through
#           [[stage_in]] so the vertex-buffer index (14+) never appears in
#           the shader source. The MSL entry point is spirv-cross's "main0".

set -eu

cd "$(dirname "$0")"

command -v glslangValidator >/dev/null || {
	echo "error: glslangValidator not found (apt/brew install glslang / glslang-tools)" >&2
	exit 1
}
command -v spirv-cross >/dev/null || {
	echo "error: spirv-cross not found (apt/brew install spirv-cross)" >&2
	exit 1
}

TMPDIR_LOCAL=$(mktemp -d)
trap 'rm -rf "$TMPDIR_LOCAL"' EXIT

glslangValidator -V uber_sdlgpu.vert -o "$TMPDIR_LOCAL/uber.vert.spv"
glslangValidator -V uber_sdlgpu.frag -o "$TMPDIR_LOCAL/uber.frag.spv"

# MSL 2.1 covers every macOS version that can also run SDL3 (10.14+).
spirv-cross --msl --msl-version 20100 "$TMPDIR_LOCAL/uber.vert.spv" \
	--output "$TMPDIR_LOCAL/uber.vert.metal"
spirv-cross --msl --msl-version 20100 "$TMPDIR_LOCAL/uber.frag.spv" \
	--output "$TMPDIR_LOCAL/uber.frag.metal"

python3 - "$TMPDIR_LOCAL" << 'EOF'
import sys, os

tmp = sys.argv[1]

def bin_array(path, name):
    data = open(path, 'rb').read()
    lines = []
    for i in range(0, len(data), 12):
        lines.append('\t' + ', '.join(f'0x{b:02x}' for b in data[i:i+12]) + ',')
    body = '\n'.join(lines)
    return (f'inline constexpr unsigned char {name}[] = {{\n{body}\n}};\n'
            f'inline constexpr unsigned int {name}_len = {len(data)};\n')

def text_blob(path, name):
    text = open(path, 'r').read()
    # Raw string literal; MSL never contains the delimiter below.
    return f'inline constexpr char {name}[] = R"MSL({text})MSL";\n'

out = []
out.append('// Generated by build_shaders.sh - DO NOT EDIT BY HAND.\n')
out.append('// Source: uber_sdlgpu.vert / uber_sdlgpu.frag (Vulkan GLSL).\n')
out.append('// SPIR-V for the Vulkan backend, MSL source for the Metal backend.\n')
out.append('#ifndef CLIENT_WARFARE_SHADERBLOBSSDLGPU_H\n')
out.append('#define CLIENT_WARFARE_SHADERBLOBSSDLGPU_H\n\n')
out.append('namespace shader_blobs\n{\n\n')
out.append(bin_array(os.path.join(tmp, 'uber.vert.spv'), 'UBER_VERT_SPIRV'))
out.append('\n')
out.append(bin_array(os.path.join(tmp, 'uber.frag.spv'), 'UBER_FRAG_SPIRV'))
out.append('\n')
out.append(text_blob(os.path.join(tmp, 'uber.vert.metal'), 'UBER_VERT_MSL'))
out.append('\n')
out.append(text_blob(os.path.join(tmp, 'uber.frag.metal'), 'UBER_FRAG_MSL'))
out.append('\n} // namespace shader_blobs\n\n')
out.append('#endif // CLIENT_WARFARE_SHADERBLOBSSDLGPU_H\n')

with open('ShaderBlobsSDLGPU.h', 'w') as f:
    f.write(''.join(out))
print(f'ShaderBlobsSDLGPU.h regenerated ({os.path.getsize("ShaderBlobsSDLGPU.h")} bytes)')
EOF
